# Generated by Django 4.2.8 on 2024-01-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approach',
            new_name='approved',
        ),
    ]
